on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "upstream",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
      - name: main
        run: |
          cd ${{ inputs.folder }}
          mvn --batch-mode --update-snapshots deploy
