on:
  push:
    paths:
      - 'void/**'
      - '.github/workflows/abstract.yml'
      - '.github/workflows/void.yml'
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/abstract.yml
    with:
      folder: void
